In [1]:
import numpy as np
import cv2 
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import sys
import os
print('modules imported')

modules imported


In [2]:
Datadirectory="test_set/"
classes=['close_eyes','open_eyes']
for category in classes:
    path=os.path.join(Datadirectory,category)
    for image in os.listdir(path):
        img=cv2.imread(os.path.join(path,image),0)
        backtorgb=cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)
        
        break
    break

In [3]:
#reading all the images and resizing 

In [4]:
training_data=[]
image_size=28

def create_training_data():
    for category in classes:
        path=os.path.join(Datadirectory,category)
        class_num=classes.index(category)
        for image in os.listdir(path):
            try:
                img=cv2.imread(os.path.join(path,image),0)
                backtorgb=cv2.cvtColor(img,cv2.COLOR_GRAY2RGB)
                new_img=cv2.resize(backtorgb,(image_size,image_size))
                training_data.append([new_img,class_num])
            except Exception as e:
                pass            

In [5]:
create_training_data()

In [6]:
print(len(training_data))

2003


In [7]:
import random
random.shuffle(training_data)


In [8]:
x=[]
y=[]

for features,labels in training_data:
    x.append(features)
    y.append(labels)

In [9]:
x=np.array(x)
y=np.array(y)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5,random_state=20)

In [12]:
x_train

array([[[[ 53,  53,  53],
         [ 51,  51,  51],
         [ 54,  54,  54],
         ...,
         [ 91,  91,  91],
         [ 91,  91,  91],
         [ 95,  95,  95]],

        [[ 50,  50,  50],
         [ 51,  51,  51],
         [ 51,  51,  51],
         ...,
         [ 96,  96,  96],
         [ 92,  92,  92],
         [ 93,  93,  93]],

        [[ 49,  49,  49],
         [ 53,  53,  53],
         [ 52,  52,  52],
         ...,
         [ 94,  94,  94],
         [ 97,  97,  97],
         [ 93,  93,  93]],

        ...,

        [[ 65,  65,  65],
         [ 70,  70,  70],
         [ 71,  71,  71],
         ...,
         [ 75,  75,  75],
         [ 75,  75,  75],
         [ 75,  75,  75]],

        [[ 65,  65,  65],
         [ 69,  69,  69],
         [ 73,  73,  73],
         ...,
         [ 76,  76,  76],
         [ 73,  73,  73],
         [ 73,  73,  73]],

        [[ 66,  66,  66],
         [ 70,  70,  70],
         [ 74,  74,  74],
         ...,
         [ 72,  72,  72],
        

In [13]:
y_train

array([1, 0, 1, ..., 0, 1, 0])

In [14]:
x_test

array([[[[ 86,  86,  86],
         [ 86,  86,  86],
         [ 84,  84,  84],
         ...,
         [ 48,  48,  48],
         [ 48,  48,  48],
         [ 43,  43,  43]],

        [[ 89,  89,  89],
         [ 87,  87,  87],
         [ 89,  89,  89],
         ...,
         [ 48,  48,  48],
         [ 49,  49,  49],
         [ 44,  44,  44]],

        [[ 91,  91,  91],
         [ 91,  91,  91],
         [ 90,  90,  90],
         ...,
         [ 49,  49,  49],
         [ 50,  50,  50],
         [ 44,  44,  44]],

        ...,

        [[ 68,  68,  68],
         [ 65,  65,  65],
         [ 66,  66,  66],
         ...,
         [ 69,  69,  69],
         [ 68,  68,  68],
         [ 64,  64,  64]],

        [[ 68,  68,  68],
         [ 63,  63,  63],
         [ 64,  64,  64],
         ...,
         [ 68,  68,  68],
         [ 67,  67,  67],
         [ 64,  64,  64]],

        [[ 68,  68,  68],
         [ 64,  64,  64],
         [ 61,  61,  61],
         ...,
         [ 68,  68,  68],
        

In [15]:
y_test

array([1, 0, 1, ..., 1, 1, 1])

In [16]:
x_train=x_train/255.0
x_test=x_test/255.0

In [17]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import models
from tensorflow.keras import layers

In [18]:
model = tf.keras.models.Sequential()

In [19]:
x_train.shape

(1001, 28, 28, 3)

In [20]:
x_test.shape

(1002, 28, 28, 3)

In [21]:
y_train.shape

(1001,)

In [22]:
y_test.shape

(1002,)

In [23]:
final_label= y_train.reshape(-1,1)

In [24]:
final_label.shape

(1001, 1)

In [25]:
model.add(keras.layers.Conv2D(64,kernel_size=3,activation='relu',input_shape=(28,28,3)))
model.add(keras.layers.Conv2D(32,kernel_size=3,activation='relu'))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(2,activation='softmax'))

In [26]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [27]:
model.fit(x_train,final_label, epochs=10)

Epoch 1/10
32/32 [==============================] - 4s 83ms/step - loss: 0.6708 - accuracy: 0.5764
Epoch 2/10
32/32 [==============================] - 3s 87ms/step - loss: 0.4134 - accuracy: 0.8250
Epoch 3/10
32/32 [==============================] - 3s 82ms/step - loss: 0.2458 - accuracy: 0.9229
Epoch 4/10
32/32 [==============================] - 3s 82ms/step - loss: 0.1992 - accuracy: 0.9266
Epoch 5/10
32/32 [==============================] - 3s 81ms/step - loss: 0.1228 - accuracy: 0.9491
Epoch 6/10
32/32 [==============================] - 3s 85ms/step - loss: 0.1085 - accuracy: 0.9561
Epoch 7/10
32/32 [==============================] - 3s 84ms/step - loss: 0.1050 - accuracy: 0.9483
Epoch 8/10
32/32 [==============================] - 3s 82ms/step - loss: 0.0899 - accuracy: 0.9618
Epoch 9/10
32/32 [==============================] - 3s 84ms/step - loss: 0.1106 - accuracy: 0.9475
Epoch 10/10
32/32 [==============================] - 3s 82ms/step - loss: 0.0765 - accuracy: 0.9649


In [28]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 64)        1792      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 24, 24, 32)        18464     
_________________________________________________________________
flatten (Flatten)            (None, 18432)             0         
_________________________________________________________________
dense (Dense)                (None, 2)                 36866     
Total params: 57,122
Trainable params: 57,122
Non-trainable params: 0
_________________________________________________________________


In [29]:
p=model.predict(x_test)
p[100]

array([0.28674048, 0.7132595 ], dtype=float32)

In [30]:
from tensorflow.keras.preprocessing.image import img_to_array
img= cv2.imread(r"C:\Users\HP\Desktop\pro\test_set\open_eyes\s0001_01845_0_0_1_0_0_01.png")
img=cv2.resize(img,(28,28))
print(img.shape)
img=img_to_array(img)
new_img=img/255.0
print(new_img.shape)
new_img = np.asarray(new_img).reshape(1, 28, 28, 3)
print(new_img.shape)

(28, 28, 3)
(28, 28, 3)
(1, 28, 28, 3)


In [31]:
predict=model.predict(new_img)

In [32]:
predict # 0.9973605 ,0.00263946

array([[0.0636799, 0.9363201]], dtype=float32)

In [33]:
predict[0]

array([0.0636799, 0.9363201], dtype=float32)

In [34]:
y_test

array([1, 0, 1, ..., 1, 1, 1])

In [36]:
from pygame import mixer
import time
mixer.init()
sound = mixer.Sound('alarm.wav')
face = cv2.CascadeClassifier(r"C:\Users\HP\Desktop\sheetal\deep_learning\opencv\cascade\haarcascade_frontalface_default.xml")
leye = cv2.CascadeClassifier(r"C:\Users\HP\Desktop\sheetal\deep_learning\opencv\cascade\haarcascade_lefteye_2splits.xml")
reye = cv2.CascadeClassifier(r"C:\Users\HP\Desktop\sheetal\deep_learning\opencv\cascade\haarcascade_righteye_2splits.xml")
lbl=['Close','Open']

cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
count=0
score=0
thicc=2
rpred=[99]
lpred=[99]
while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face.detectMultiScale(gray,minNeighbors=5,scaleFactor=1.1,minSize=(28,28))
    left_eye = leye.detectMultiScale(gray)
    right_eye = reye.detectMultiScale(gray)
    cv2.rectangle(frame, (0,height-50) , (200,height) , (0,0,0) , thickness=cv2.FILLED )
    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (100,100,100) , 1 )
    for (x,y,w,h) in right_eye:
        r_eye=frame[y:y+h,x:x+w]
        count=count+1
        #r_eye = cv2.cvtColor(r_eye,cv2.COLOR_BGR2GRAY)
        r_eye = cv2.resize(r_eye,(28,28))
        r_eye= r_eye/255.0
        r_eye= r_eye.reshape(28,28,-1)  
       
        # final_image=np.expand_dims(final_image,axis=0)
       # final_image=final_image/255.0
        r_eye = np.expand_dims(r_eye,axis=0)
        rpred = model.predict_classes(r_eye)
        if(rpred[0]==1):
            lbl='Open'
        if(rpred[0]==0):
            lbl='Closed'
        break
    for (x,y,w,h) in left_eye:
        l_eye=frame[y:y+h,x:x+w]
        count=count+1
        #l_eye = cv2.cvtColor(l_eye,cv2.COLOR_BGR2GRAY)
        l_eye = cv2.resize(l_eye,(28,28))
        l_eye= l_eye/255.0
        l_eye= l_eye.reshape(28,28,-1)
        l_eye = np.expand_dims(l_eye,axis=0)
        lpred = model.predict_classes(l_eye)
        if(lpred[0]==1):
            lbl='Open'
        if(lpred[0]==0):
            lbl='Closed'
        break
    if(rpred[0]==0 and lpred[0]==0):
        score=score+1
        cv2.putText(frame,"Closed",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    # if(rpred[0]==1 or lpred[0]==1):
    else:
        score=score-1
        cv2.putText(frame,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    if(score<0):
        score=0
    cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    if(score>8):
        #person is feeling sleepy so we beep the alarm
        cv2.imwrite(os.path.join(path,'image.jpg'),frame)
        try:
            sound.play()
        except: # isplaying = False
            pass
        if(thicc<16):
            thicc= thicc+2
        else:
            thicc=thicc-2
            if(thicc<2):
                thicc=2
        cv2.rectangle(frame,(0,0),(width,height),(0,0,255),thicc)
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()